# Generated by Django 4.1.2 on 2022-11-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StellarApp', '0003_admindb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindb',
            name='Image',
        ),
    ]
