# Generated by Django 4.1.2 on 2022-11-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StellarApp', '0004_remove_admindb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
