# Generated by Django 4.1.2 on 2022-12-14 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StellarApp', '0009_logindb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproductdb',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='logindb',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='logindb',
            old_name='Username',
            new_name='username',
        ),
    ]
