# Generated by Django 4.1.2 on 2022-12-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StellarApp', '0010_rename_price_addproductdb_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproductdb',
            old_name='price',
            new_name='Price',
        ),
    ]
