# Generated by Django 4.1.2 on 2023-01-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StellarApp', '0011_rename_price_addproductdb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproductdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
